version: '3.8'

services:
  postgres-db:
    image: postgres:17.5-alpine3.22
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=madhav
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - E:/symptomSync-storage/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis-db:
    image: redis:8.0.3-alpine
    container_name: redis-db
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - E:/symptomSync-storage/redis-data:/data
    restart: unless-stopped
