version: '3.8'

services:
  postgres-db:
    image: postgres:17.5-alpine3.22
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - symptomSync_backend
    restart: unless-stopped

  redis-db:
    image: redis:8.0.3-alpine
    container_name: redis-db
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-admin}
    volumes:
      - redisdata:/data
    networks:
      - symptomSync_backend
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:

networks:
  symptomSync_backend:
