from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle


def generate_patient_report_pdf(
    name,
    age,
    gender,
    symptoms,
    medical_history,
    medications,
    appointment_date,
    appointment_time,
    appointment_number,
    output_path="patient_report.pdf",
):
    def safe(v):
        if v is None:
            return "Not provided"
        if isinstance(v, str) and not v.strip():
            return "Not provided"
        return str(v)

    name = safe(name)
    age = safe(age)
    gender = safe(gender)
    symptoms = safe(symptoms)
    medical_history = safe(medical_history)
    medications = safe(medications)
    appointment_date = safe(appointment_date)
    appointment_time = safe(appointment_time)
    appointment_number = safe(appointment_number)
    generated_on = datetime.now().strftime("%Y-%m-%d %H:%M")

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
    )

    styles = getSampleStyleSheet()
    title_style = styles["Title"]
    heading_style = styles["Heading2"]
    body_style = styles["BodyText"]

    small_style = ParagraphStyle(
        "Small", parent=body_style, fontSize=9, leading=12, textColor=colors.grey
    )

    story = []

    story.append(Paragraph("Patient Appointment Report", title_style))
    story.append(Spacer(1, 6))

    meta_table = Table(
        [
            ["Booking ID", appointment_number],
            ["Generated On", generated_on],
        ],
        colWidths=[45 * mm, 120 * mm],
    )
    meta_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#EAEAEA")),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#BDBDBD")),
                ("PADDING", (0, 0), (-1, -1), 6),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    story.append(meta_table)
    story.append(Spacer(1, 12))

    story.append(Paragraph("Patient Information", heading_style))
    patient_info = Table(
        [
            ["Name", name],
            ["Age", age],
            ["Gender", gender],
        ],
        colWidths=[45 * mm, 120 * mm],
    )
    patient_info.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F4F4F4")),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D0D0D0")),
                ("PADDING", (0, 0), (-1, -1), 6),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    story.append(patient_info)
    story.append(Spacer(1, 12))

    story.append(Paragraph("Appointment Details", heading_style))
    appointment_info = Table(
        [
            ["Date", appointment_date],
            ["Time", appointment_time],
            ["Booking Reference", appointment_number],
        ],
        colWidths=[45 * mm, 120 * mm],
    )
    appointment_info.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F4F4F4")),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D0D0D0")),
                ("PADDING", (0, 0), (-1, -1), 6),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    story.append(appointment_info)
    story.append(Spacer(1, 12))

    story.append(Paragraph("Reported Symptoms", heading_style))
    story.append(Paragraph(symptoms.replace("\n", "<br/>"), body_style))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Medical History", heading_style))
    story.append(Paragraph(medical_history.replace("\n", "<br/>"), body_style))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Current Medications", heading_style))
    story.append(Paragraph(medications.replace("\n", "<br/>"), body_style))
    story.append(Spacer(1, 14))

    disclaimer = (
        "This report was auto-generated by the Patient Assistant system for "
        "administrative and scheduling purposes only. It does not constitute "
        "a medical record, diagnosis, or clinical assessment."
    )
    story.append(Paragraph(disclaimer, small_style))

    doc.build(story)
    return output_path
